services:
  - type: web
    name: exoplanet-hunters-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd astronet-cnn-v3/exoplanet-ml && python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
